### ISSUE TITLE
enhancement(authentication): Easy movement between login and registration

### ISSUE THREAD

**Issue by mrapacz** [forcecraft/aion#111]
**Type**

Enhancement

**Current behaviour**
When someone enters our page for the first time, he/she doesn't know how to log in (they have no account) and they get redirected to /login. 

**Expected behaviour**
They should be redirected to /register or/and there should be an information saying `Already registered. Log in here` and `No account yet? Register here.` on both of these so that the user doesn't feel lost.

**Motivation / use case**
Fundamental UX

**Comment by pmrukot** [comment]
Can we close this as it was introduced in #126 ?

**Comment by mrapacz** [comment]
Yes.
