### ISSUE TITLE
enhancement(authentication): Logout

### ISSUE THREAD

**Issue by mrapacz** [forcecraft/aion#112]
**Type**

Enhancement

**Current behaviour**
There's no way to log out right now (unless you want to wait for your token to expire or you want to clear your browser cookies.

**Expected behaviour**
There should be a button enabling you to log out.

**Motivation / use case**
Fundamental UX

**Comment by pmrukot** [comment]
Resolved in #126 Can we close?

**Comment by mrapacz** [comment]
Yes. I guess all the issues should have been marked in the PR to be closed automagically.
