### ISSUE TITLE
fix(elixir): Fix display of login page in firefox

### ISSUE THREAD

**Issue by klausweiss** [forcecraft/aion#113]
**Environment**
Ubuntu 16.04, Firefox 54.0

**Type**

Bug

**Current behaviour**
![image](https://user-images.githubusercontent.com/11031002/30294997-5d028416-973f-11e7-843d-043471bc05ae.png)

**Expected behaviour**

![image](https://user-images.githubusercontent.com/11031002/30295013-6df65e6e-973f-11e7-92ae-6f301859b37a.png)

**Motivation / use case**

It's ugly.

**Comment by mrapacz** [comment]
This issue should be solved during #87 and #111. Thanks for reporting!

**Comment by pmrukot** [comment]
Should not be an issue anymore since we replaced Addict forms in #126
