### ISSUE TITLE
fix(elm): No images displayed in Firefox

### ISSUE THREAD

**Issue by klausweiss** [forcecraft/aion#114]
**Environment**
Ubuntu 16.04, Firefox 54.0

**Type**

Bug

**Current behaviour**
![image](https://user-images.githubusercontent.com/11031002/30295251-3da98a0a-9740-11e7-8246-42badf6e8e6d.png)

**Expected behaviour**
![image](https://user-images.githubusercontent.com/11031002/30295264-4a96b102-9740-11e7-9491-0e34d2a3b294.png)

**Motivation / use case**
I was expecting an image but no file was found ):

**Comment by mrapacz** [comment]
Thanks for reporting, we'll look into that and fix it before releasing an official version of our app :+1:

**Comment by mrapacz** [comment]
Just tested it in Firefox and it worked, so I call it fixed. 
![image](https://user-images.githubusercontent.com/15965147/31852323-00fcdaee-b676-11e7-93b5-0891194443e4.png)
