### ISSUE TITLE
[UX/UI] Delete workspace view, disable endpoints

### ISSUE THREAD

**Issue by pmrukot** [forcecraft/aion#136]
**Type**
Enhancement

**Motivation / use case**
Due to recent shift of priorities in development we want to focus more on gameplay and user statistics rather than possibility to create resources. Thus, the decision was made to disable workspace view. We should also disable endpoints for creating any resource.

_At least for now_

**Comment by mrapacz** [comment]
_At least for now_ :1st_place_medal:
