### ISSUE TITLE
[UX/UI] Improve login and registration pages

### ISSUE THREAD

**Issue by pmrukot** [forcecraft/aion#137]
**Type**
Enhancement

**Motivation / use case**
Current login/registration page is really basic. Its a first view that user sees - it should be clear and drag attention.

- [ ] Include branding for consistency (Aion + logo)
- [ ] Include navbar for consistency
- [ ] Toggle button should not jump around when switching context from login to register
- [ ] Add project description to give information to user what is he logging into (good inspo of what we could become: https://whybluesky.net/sign-up)

**Comment by mrapacz** [comment]
Sounds great, we will have to think about what to put as the project description :+1:
