### ISSUE TITLE
[UX/UI] Move rooms view to the home page after login

### ISSUE THREAD

**Issue by pmrukot** [forcecraft/aion#138]
**Type**
Enhancement

**Motivation / use case**
There is a lot of reasons for doing that:
- It shows main content of the platform and lets user get straight to the actual game, which is closer to original JPKS
- We do not want to have "workspace" view anymore
- Profile can be accessible via navbar (do not need for a card or hyperlink in main view)

**Comment by mrapacz** [comment]
This one is golden

**Comment by mrapacz** [comment]
@pmrukot do we also want to remove the `Rooms` tab? 

Right now the Aion logo and Rooms are the same urls (which was confusing for me when I clicked on `Rooms` and nothing happened, I realised after a moment that there is no special room list view anymore)
