### ISSUE TITLE
[UX/UI] Make room tiles same colour

### ISSUE THREAD

**Issue by pmrukot** [forcecraft/aion#142]
**Type**
Enhancement

**Motivation / use case**
Our rooms view is currently filled with tiles with randomised colours which is good example of bad UX. Different colours/shades may indicate that the rooms' difficulty varies or type of questions are different.

Making it same colour also has a disadvantage of more boring look but that's better than misleading UX.

**Comment by mrapacz** [comment]
@pmrukot did we get any suggestions on the color scheme?

**Comment by mrapacz** [comment]
Ah sorry, I can see this topic is kinda touched in #135, will move the discussion there.
