### ISSUE TITLE
[UX/UI] Restore room creation functionality

### ISSUE THREAD

**Issue by pmrukot** [forcecraft/aion#193]
**Type**
Feature

**Description**
Title

**Motivation / use case**
Demo purpose

**Comment by mrapacz** [comment]
Remember to make it as simple as possible - this time there should be no choice in the categories (should take all by default), the player only specifies the name.

**Comment by pmrukot** [comment]
For demo purpose I would go with the form we had before, when we release it we could strip it down to what you've mentioned.

**Comment by mrapacz** [comment]
Agreed, let's do it.
