### ISSUE TITLE
Token przypal

### ISSUE THREAD

**Issue by ghost** [forcecraft/aion#211]
**Type**
Bug 

**Current behaviour**
Elo mordy

Wbijam sobie do Was na stronke a tu przypal https://ibb.co/mUWtib , wyczyscilem dane przegladarki i tak samo! Cos popsuliscie z tokenami :[ Ubuntu 16.04 + chrome. 

**Expected behaviour**

**Motivation / use case**

**Comment by ghost** [comment]
@pmrukot

**Comment by mrapacz** [comment]
#212 should work just fine to fix the issue
