### ISSUE TITLE
enhancement(elixir): Introduce elixir linter

### ISSUE THREAD

**Issue by mrapacz** [forcecraft/aion#51]
**Type**

Enhancement

**Current behaviour**

There is no automatic code formatter for Elixir, so we need a tool to make sure our code style is cohesive in all modules. There are two options I've managed to find so far:
  * [Dogma](https://github.com/lpil/dogma)
  * [Credo](https://github.com/rrrene/credo)

Please find attached the results of running both of these on our current master and tell me, which one in your opinion will fit better to our current state of the project.

[Results of Dogma](https://github.com/pmrukot/aion/files/1150444/dogma.txt)
[Results of Credo](https://github.com/pmrukot/aion/files/1150458/credo.txt)

**Comment by mrapacz** [comment]
@pmrukot check these out

**Comment by pmrukot** [comment]
We should go with Dogma IMO, especially after reading: http://trivelop.de/2015/11/26/comparison-dogma-credo/

**Comment by mrapacz** [comment]
Actually, this article is biased in the direction of Credo, how did it make you want to use Dogma?

**Comment by pmrukot** [comment]
Yeah, I meant Credo 😑
