### ISSUE TITLE
feature(elixir): Introduce dialyxir

### ISSUE THREAD

**Issue by mrapacz** [forcecraft/aion#70]
**Type**

Feature

**Description**
Right now we have no mechanism for type checking and it's hard to know all the time what data structures we are operating on on the backend side. The idea is to introduce typespecs which would both:
 - help us understand what are the data structures, what fields they have etc.
 - diminish the number of bugs we make, because we could check if our functions take and return what we declared they would 

The weapon of my choice would be [**dialyxir**](https://github.com/jeremyjh/dialyxir)

**Comment by pmrukot** [comment]
Im all for that change 👍
