### ISSUE TITLE
general(aion): Transfer repo to forcecraft

### ISSUE THREAD

**Issue by mrapacz** [forcecraft/aion#83]
**Type**

Enhancement

**Current behaviour**
Our repo belongs to @pmrukot right now, which makes it impossible for me or @jtkpiotr to change profile picture of the repo, add new CI etc. because we don't have permissions.

**Expected behaviour**
We should all have admin access to our repository.

**Motivation / use case**
Such things like profile picture should not require us to ask @pmrukot to do it for us.

**Comment by pmrukot** [comment]
![](https://media.giphy.com/media/CpxCYD0Or2Ty8/giphy.gif)

**Comment by mrapacz** [comment]
![giphy 2](https://user-images.githubusercontent.com/15965147/29632958-df8d61c6-8844-11e7-98f9-769fdc669211.gif)
