### ISSUE TITLE
enhancement(design): Reiterate with Aion design

### ISSUE THREAD

**Issue by pmrukot** [forcecraft/aion#87]
**Type**

Enhancement

**Motivation / use case**

After closing https://github.com/forcecraft/aion/issues/32 we need to reiterate and improve design of our application - probably consult it with someone from outside the team since no one here has good knowledge of UX/UI.

**Comment by mrapacz** [comment]
Closing this one, as a whole [new milestone](https://github.com/forcecraft/aion/milestone/5) was created for that/=.
