### ISSUE TITLE
fix(elm): Handle reload

### ISSUE THREAD

**Issue by mrapacz** [forcecraft/aion#89]
**Type**

Fix

**Current behaviour**
If we are present in one of the rooms and we refresh the page, the game crashes for the player. He is in the room, but he's not connected to the Phoenix channel. We need to handle it somehow.

**Expected behaviour**

*QUESTION*
How should we react to user hitting F5 during the gameplay? Should we: 
 - ask him to confirm that he wants to refresh, then refresh and zero his game progress?
 - do nothing (just ignore the refresh or refresh, but make sure that the state stays the same)
 - ask him to confirm and then redirect him back to the room lobby / main 

Not sure if each one of these is possible to be implemented. Also not sure which approach is the best. That's why we need to settle it first, before implementing any of the solutions.
@pmrukot @jtkpiotr 

**Motivation / use case**
![giphy 6](https://user-images.githubusercontent.com/15965147/29749709-9e100938-8b32-11e7-923d-fe701a64f740.gif)

**Comment by pmrukot** [comment]
Was this resolved with: https://github.com/forcecraft/aion/pull/86 ?

**Comment by mrapacz** [comment]
Yes, I figured that moving the tickets using huboard to 'done' section will also close them, but apparently it's not the case. Closing.
